export const mapStyles: google.maps.MapTypeStyle[] = [
    { elementType: "geometry", stylers: [{ color: "#171b22" }] },
    { elementType: "labels.text.fill", stylers: [{ color: "#b6bdc9" }] },
    { elementType: "labels.text.stroke", stylers: [{ color: "#171b22" }] },
    { elementType: "labels.icon", stylers: [{ visibility: "off" }] },
    { featureType: "road", elementType: "geometry", stylers: [{ color: "#303744" }] },
    { featureType: "road.highway", elementType: "geometry", stylers: [{ color: "#475263" }] },
    { featureType: "road", elementType: "labels.text.fill", stylers: [{ color: "#c8cfdb" }] },
    { featureType: "water", elementType: "geometry", stylers: [{ color: "#090e17" }] },
    { featureType: "water", elementType: "labels.text.fill", stylers: [{ color: "#8b9cb3" }] },
    { featureType: "poi.park", elementType: "geometry", stylers: [{ color: "#1c2b27" }] },
    { featureType: "poi", elementType: "labels", stylers: [{ visibility: "off" }] },
    { featureType: "transit", stylers: [{ visibility: "off" }] },
    { featureType: "administrative", elementType: "geometry.stroke", stylers: [{ color: "#555e6e" }] },
];
